name: Build and Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout code ---
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- API ---
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build API
        run: mvn clean install
        working-directory: ./StudentDashboard-api

      - name: SonarCloud Scan API
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: StudentDashboard-api
          args: >
            -Dsonar.organization=santhosh1277
            -Dsonar.projectKey=StudentDashboard-API
            -Dsonar.projectName=" StudentDashboard-api"
            -Dsonar.sources=src

      # --- UI ---
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install UI dependencies
        run: npm install
        working-directory: ./StudentDashboard-ui

      - name: Build React UI
        run: npm run build
        working-directory: ./StudentDashboard-ui

      - name: SonarCloud Scan UI
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: StudentDashboard-ui
          args: >
            -Dsonar.organization=santhosh1277
            -Dsonar.projectKey=StudentDashboard-UI
            -Dsonar.projectName="StudentDashboard UI"
            -Dsonar.sources=src
