name: Build and Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # --- API Build ---
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build API
        run: mvn clean install
        working-directory: ./StudentDashboard-api

      # SonarCloud scan for API
      - name: SonarCloud Scan API
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: santhosh1277
          projectKey: StudentDashboard-API
          projectName: "StudentDashboard API"
          projectBaseDir: StudentDashboard-api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # --- UI Build ---
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install UI dependencies
        run: npm install
        working-directory: ./StudentDashboard-ui

      - name: Build React UI
        run: npm run build
        working-directory: ./StudentDashboard-ui

      # SonarCloud scan for UI
      - name: SonarCloud Scan UI
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: santhosh1277
          projectKey: StudentDashboard-UI
          projectName: "StudentDashboard UI"
          projectBaseDir: StudentDashboard-ui
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
