name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ------------------- FRONTEND (React) -------------------
  sonar-ui:
    name: Scan Frontend (React)
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: student-dashboard-ui
        run: npm install

      - name: Run SonarCloud scan (UI)
        working-directory: student-dashboard-ui
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=santhosh1277_AgileProjectTeamMavericks_UI \
            -Dsonar.organization=santhosh1277 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  # ------------------- BACKEND (Spring Boot) -------------------
  sonar-api:
    name: Scan Backend (Spring Boot)
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build Backend
        run: mvn -f StudentDashboard-api/pom.xml clean verify

      - name: Run SonarCloud scan (API)
        working-directory: StudentDashboard-api
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=santhosh1277_AgileProjectTeamMavericks \
          -Dsonar.organization=santhosh1277 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
